version: '3.9'

services:
  mongodb-dev:
    image: mongo:latest
    container_name: mongodb-dev
    restart: unless-stopped
    env_file:
      - ./.env.db
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    volumes:
      - mongodb_data_container:/data/db
      - type: bind
        source: ../init-mongo.sh
        target: /docker-entrypoint-initdb.d/init-mongo.sh
        read_only: true
    networks:
      - appetizer-dev

  tc-appetizer-dev:
    image: tc-appetizer:${VERSION:-latest}
    restart: unless-stopped
    environment:
      PORT: $PORT
    ports:
      - $PORT:$PORT
    env_file:
      - ./.env.proc
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    depends_on:
      - mongodb-dev
    networks:
      - appetizer-dev

volumes:
  mongodb_data_container:

networks:
  appetizer-dev:
   driver: bridge
